---
name: Sunny Side Up - GetSiteControl
---
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - Sunnysideup\GetSiteControl\Extensions\SiteConfigExtension

Silverstripe\CMS\Model\SiteTree:
  extensions:
    - Sunnysideup\GetSiteControl\Extensions\PageExtension

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Sunnysideup\GetSiteControl\Extensions\PageControllerExtension
