---
name: ssu_getsitecontrol
---
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - Sunnysideup\GetSiteControl\Extensions\SiteConfigExtension

Silverstripe\CMS\Model\SiteTree:
  extensions:
    - Sunnysideup\GetSiteControl\Extensions\PageExtension
Page:
  extensions:
    - Sunnysideup\GetSiteControl\Extensions\PageControllerExtension